language: csharp
mono: none
dotnet: 2.2.402
solution: ArchUnit.sln
script: chmod +x ./Travis/build.sh && ./Travis/build.sh $NUGET_API_KEY
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./Travis/deploy.sh && ./Travis/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    tags: true
    all_branches: true
